#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Custom Script Processor
Allows users to create videos based on custom scripts in Bengali
"""

import os
import logging
import datetime
import uuid
import json
import subprocess
from pathlib import Path

# --- Configuration ---
# এই ডিরেক্টরিগুলো Render-এর ফাইল সিস্টেমে তৈরি হবে
OUTPUT_DIR = "/var/data/output"
TEMP_DIR = "/var/data/temp"
SCRIPTS_DIR = os.path.join(os.getcwd(), "scripts") # প্রজেক্টের সাথে scripts ফোল্ডার রাখুন
FONT_PATH = os.path.join(os.getcwd(), "fonts/SiyamRupali.ttf") # প্রজেক্টের সাথে font ফাইল রাখুন

VIDEO_WIDTH = 1280
VIDEO_HEIGHT = 720
VIDEO_FPS = 25

# --- Setup Logging ---
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

def ensure_directory_exists(directory_path):
    """Ensure a directory exists, creating it if necessary."""
        Path(directory_path).mkdir(parents=True, exist_ok=True)

        def sanitize_filename(filename):
            """Remove characters that are invalid for filenames."""
                return "".join(c for c in filename if c.isalnum() or c in (' ', '_', '-')).rstrip()

                def generate_bengali_speech(text, audio_file_path):
                    """
                        Generate Bengali speech using gTTS.
                            NOTE: You need to install gTTS: pip install gTTS
                                """
                                    try:
                                            from gtts import gTTS
                                                    tts = gTTS(text=text, lang='bn', slow=False)
                                                            tts.save(audio_file_path)
                                                                    logging.info(f"Generated speech successfully: {audio_file_path}")
                                                                            return audio_file_path
                                                                                except ImportError:
                                                                                        logging.error("gTTS library not found. Please install it using: pip install gTTS")
                                                                                                return None
                                                                                                    except Exception as e:
                                                                                                            logging.error(f"Error generating speech: {str(e)}")
                                                                                                                    return None

                                                                                                                    def create_segment_video(segment, segment_index, video_type):
                                                                                                                        """
                                                                                                                            Create a single video segment from a script segment.
                                                                                                                                """
                                                                                                                                    try:
                                                                                                                                            content = segment.get("content", "কোনো কনটেন্ট নেই")
                                                                                                                                                    duration = segment.get("duration", 10) # সেকেন্ডে ডিউরেশন

                                                                                                                                                            unique_id = str(uuid.uuid4())[:8]
                                                                                                                                                                    audio_file = os.path.join(TEMP_DIR, f"audio_{segment_index}_{unique_id}.mp3")

                                                                                                                                                                            # Generate audio for the segment
                                                                                                                                                                                    if not generate_bengali_speech(content, audio_file):
                                                                                                                                                                                                logging.error(f"Failed to generate speech for segment {segment_index}")
                                                                                                                                                                                                            return None

                                                                                                                                                                                                                    segment_video = os.path.join(TEMP_DIR, f"segment_{segment_index}_{unique_id}.mp4")

                                                                                                                                                                                                                            # Select background color based on video type
                                                                                                                                                                                                                                    bg_colors = {
                                                                                                                                                                                                                                                    "cartoon": "skyblue",
                                                                                                                                                                                                                                                                "anime": "lightpink",
                                                                                                                                                                                                                                                                            "real": "forestgreen",
                                                                                                                                                                                                                                                                                        "news": "navy"
                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                            bg_color = bg_colors.get(video_type, "black")

                                                                                                                                                                                                                                                    # FFmpeg command to create video with text overlay and audio
                                                                                                                                                                                                                                                            # Using a Bengali font file (SiyamRupali.ttf) included in the project
                                                                                                                                                                                                                                                                    cmd = [
                                                                                                                                                                                                                                                                                    "ffmpeg", "-y",
                                                                                                                                                                                                                                                                                                "-f", "lavfi", "-i", f"color=c={bg_color}:s={VIDEO_WIDTH}x{VIDEO_HEIGHT}:d={duration}",
                                                                                                                                                                                                                                                                                                            "-i", audio_file,
                                                                                                                                                                                                                                                                                                                        "-vf", f"drawtext=fontfile='{FONT_PATH}':text='{content}':fontcolor=white:fontsize=48:x=(w-text_w)/2:y=(h-text_h)/2:box=1:boxcolor=black@0.5:boxborderw=10",
                                                                                                                                                                                                                                                                                                                                    "-c:v", "libx264", "-preset", "fast", "-crf", "23",
                                                                                                                                                                                                                                                                                                                                                "-c:a", "aac", "-b:a", "192k",
                                                                                                                                                                                                                                                                                                                                                            "-shortest",
                                                                                                                                                                                                                                                                                                                                                                        "-pix_fmt", "yuv420p",
                                                                                                                                                                                                                                                                                                                                                                                    segment_video
                                                                                                                                                                                                                                                                    ]

                                                                                                                                                                                                                                                                            subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)

                                                                                                                                                                                                                                                                                    if os.path.exists(segment_video):
                                                                                                                                                                                                                                                                                                logging.info(f"Created segment video: {segment_video}")
                                                                                                                                                                                                                                                                                                            return segment_video
                                                                                                                                                                                                                                                                                                                    else:
                                                                                                                                                                                                                                                                                                                                logging.error(f"Failed to create segment video {segment_index}")
                                                                                                                                                                                                                                                                                                                                            return None

                                                                                                                                                                                                                                                                                                                                                except subprocess.CalledProcessError as e:
                                                                                                                                                                                                                                                                                                                                                        logging.error(f"FFmpeg error creating segment video: {e.stderr.decode()}")
                                                                                                                                                                                                                                                                                                                                                                return None
                                                                                                                                                                                                                                                                                                                                                                    except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                            logging.error(f"Error in create_segment_video: {str(e)}")
                                                                                                                                                                                                                                                                                                                                                                                    return None

                                                                                                                                                                                                                                                                                                                                                                                    def combine_segments(segment_videos, output_video):
                                                                                                                                                                                                                                                                                                                                                                                        """Combine multiple video segments into a single video."""
                                                                                                                                                                                                                                                                                                                                                                                            try:
                                                                                                                                                                                                                                                                                                                                                                                                    if not segment_videos:
                                                                                                                                                                                                                                                                                                                                                                                                                logging.error("No segment videos to combine.")
                                                                                                                                                                                                                                                                                                                                                                                                                            return False

                                                                                                                                                                                                                                                                                                                                                                                                                                    list_file = os.path.join(TEMP_DIR, "segments_list.txt")
                                                                                                                                                                                                                                                                                                                                                                                                                                            with open(list_file, 'w', encoding='utf-8') as f:
                                                                                                                                                                                                                                                                                                                                                                                                                                                        for video in segment_videos:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        f.write(f"file '{os.path.abspath(video)}'\n")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cmd = [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "ffmpeg", "-y",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "-f", "concat", "-safe", "0",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "-i", list_file,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "-c", "copy",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                output_video
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ]

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if os.path.exists(output_video):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            logging.info(f"Combined segments successfully: {output_video}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return True
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            logging.error("Failed to combine segments.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return False

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            except subprocess.CalledProcessError as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    logging.error(f"FFmpeg error combining segments: {e.stderr.decode()}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return False
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        logging.error(f"Error in combine_segments: {str(e)}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return False

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                def process_script(script_path):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    """Process a single script file to create a complete video."""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                with open(script_path, 'r', encoding='utf-8') as f:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            script_data = json.load(f)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    title = script_data.get("title", "Untitled Video")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            video_type = script_data.get("type", "general")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    segments = script_data.get("segments", [])

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if not segments:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        logging.error(f"Script '{title}' has no segments.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return None

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Create output file path
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    safe_title = sanitize_filename(title)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    output_video = os.path.join(OUTPUT_DIR, f"{safe_title}_{timestamp}.mp4")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            segment_videos = []
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for i, segment in enumerate(segments):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                logging.info(f"Processing segment {i+1}/{len(segments)}...")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            segment_video = create_segment_video(segment, i+1, video_type)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if segment_video:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        segment_videos.append(segment_video)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if not segment_videos:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            logging.error("Failed to create any video segments.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return None

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                success = combine_segments(segment_videos, output_video)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # Cleanup temporary files
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for video in segment_videos:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if os.path.exists(video):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            os.remove(video)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if success:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                logging.info(f"Script processed successfully. Video saved at: {output_video}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # এখানে আপনি টেলিগ্রামে পাঠানোর কোড যোগ করতে পারেন
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # send_to_telegram(output_video, script_data)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return output_video
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        logging.error("Failed to process script.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return None

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                logging.error(f"Error processing script {script_path}: {str(e)}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return None

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Ensure all necessary directories exist
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ensure_directory_exists(SCRIPTS_DIR)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ensure_directory_exists(TEMP_DIR)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ensure_directory_exists(OUTPUT_DIR)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ensure_directory_exists(os.path.join(os.getcwd(), "fonts"))

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                logging.info("Script processor started.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # একটি উদাহরণ স্ক্রিপ্ট প্রসেস করা হচ্ছে
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # আপনার নিজের স্ক্রিপ্ট ফাইল এখানে রাখুন
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            example_script_path = os.path.join(SCRIPTS_DIR, "example_script.json")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if not os.path.exists(example_script_path):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # একটি নমুনা স্ক্রিপ্ট তৈরি করা হচ্ছে
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                template_script = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "title": "আমার প্রথম ভিডিও",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "type": "cartoon",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "segments": [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {"content": "সবাইকে স্বাগতম।", "duration": 5},
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {"content": "এটি একটি স্বয়ংক্রিয়ভাবে তৈরি ভিডিও।", "duration": 7},
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {"content": "ধন্যবাদ।", "duration": 4}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        with open(example_script_path, 'w', encoding='utf-8') as f:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    json.dump(template_script, f, ensure_ascii=False, indent=4)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            logging.info(f"Example script created at: {example_script_path}")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                process_script(example_script_path)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    logging.info("Script processing finished.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ]
                                                                                                                                                                                                                                                                    ]
                                                                                                                                                                                                                                    }